spring:
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: ${MAIL_SENDER}
    password: ${MAIL_SENDER_PASSWORD}
    test-connection: false
    properties:
      mail:
        smtp:
          ssl:
            enable: true