# 流程名称
name: demo

# 何时触发工作流
#- cron: "34 7 * * MON"
#- cron: "43 7 * * TUE"
#- cron: "51 7 * * WED"
#- cron: "30 7 * * THU"
#- cron: "54 7 * * FRI"
#- cron: "43 7 * * SAT"
#- cron: "39 7 * * SUN"
on:
  schedule:
    # 可以使用 https://crontab.guru 来帮助生成并确认它将在何时运行
    # - cron: "30 22 * * *" # 22+8=北京时间上午6:30
    - cron: "34 23 * * MON"
    - cron: "43 23 * * TUE"
    - cron: "51 23 * * WED"
    - cron: "30 23 * * THU"
    - cron: "54 23 * * FRI"
    - cron: "43 23 * * SAT"
    - cron: "39 23 * * SUN"
  workflow_dispatch:

env:
  MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
  MAIL_SENDER_PASSWORD: ${{ secrets.MAIL_SENDER_PASSWORD }}
  MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
  FREE_CHECKIN_TWO_USER: ${{ secrets.FREE_CHECKIN_TWO_USER }}
  FREE_CHECKIN_TWO_ENABLE: ${{ secrets.FREE_CHECKIN_TWO_ENABLE }}
  FREE_CHECKIN_TWO_URL: ${{ secrets.FREE_CHECKIN_TWO_URL }}
  FREE_CHECKIN_TWO_TOKEN: ${{ secrets.FREE_CHECKIN_TWO_TOKEN }}
  FREE_CHECKIN_TWO_COOKIE: ${{ secrets.FREE_CHECKIN_TWO_COOKIE }}

# 作业s
jobs:
  # job
  run_tests: # job 的唯一标识
    # 在 Ubuntu 环境中运行
    runs-on: ubuntu-latest
    steps:
      # 步骤：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      # 步骤：设置 Java 环境为 JDK 21，并使用 Corretto 发行版
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # 步骤：运行测试
      - name: Run tests with Maven
        run: mvn clean test