# 流程名称
name: demo

# 何时触发工作流
on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
  MAIL_SENDER_PASSWORD: ${{ secrets.MAIL_SENDER_PASSWORD }}
  MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}

# 作业s
jobs:
  # job
  run_tests: # job 的唯一标识
    # 在 Ubuntu 环境中运行
    runs-on: ubuntu-latest
    steps:
      # 步骤：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      # 步骤：设置 Java 环境为 JDK 21，并使用 Corretto 发行版
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # 步骤：运行测试
      - name: Run tests with Maven
        run: mvn clean test